name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Playwright common setup
        uses: ./.github/actions/playwright-common
      - name: Run Lint
        run: npm run lint
      - name: Run Format Check
        run: npm run format -- --check

  build:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Playwright common setup
        uses: ./.github/actions/playwright-common

  api_tests:
    runs-on: ubuntu-latest
    needs: build
    env:
      JUNIT_FILE: playwright-report/api-results.xml
    steps:
      - name: Playwright common setup
        uses: ./.github/actions/playwright-common
      - name: Run API Tests
        run: npx playwright test --project=public-api --workers=1
      - name: Upload Playwright API Report and Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-api-report
          path: |
            playwright-report/
            test-results/
          retention-days: 30

  ui_tests:
    runs-on: ubuntu-latest
    needs: api_tests
    env:
      USER_EMAIL: ${{ secrets.USER_EMAIL }}
      USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
      JUNIT_FILE: playwright-report/ui-results.xml
    steps:
      - name: Playwright common setup
        uses: ./.github/actions/playwright-common
      - name: Run UI Tests
        run: npx playwright test --project=default --workers=1
      - name: Upload Playwright UI Report and Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-ui-report
          path: |
            playwright-report/
            test-results/
          retention-days: 30
      - name: Upload Test Results Summary
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-summary
          path: playwright-report/*.xml

  notify:
    runs-on: ubuntu-latest
    needs: ui_tests
    steps:
      - name: Notify
        run: echo "✅ Tests complete. Notify step finished."
